language: ruby
dist: trusty
sudo: false
cache: bundler
before_install:
  - gem update bundler
script:
  - bundle exec rake
after_success:
  # Send coverage report from the job #1 == current MRI release
  - '[ "${TRAVIS_JOB_NUMBER#*.}" = "1" ] && [ "$TRAVIS_BRANCH" = "master" ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.6.2
  - 2.5.5
  - 2.4.5
  - jruby-9.2.6.0
addons:
  code_climate:
    repo_token: 2c2c7c253435c02667371778ca886b069d4d24590748fbd7396b9b080016bfa7
notifications:
  email: false
